name: Lint
description: 'Run lint'

runs:
  using: "composite"
  steps:
    - name: Install dependencies # install project deps with --frozen-lockfile to make sure we will have the same packages version ( very recommended  on running yarn install on ci)
      shell: bash
      run: yarn lint:ci
