name: Docs

on:
  push:
    branches: [ "docs", "main" ]

jobs:
  docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 20.11.x ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Install dependencies # install project deps with --frozen-lockfile to make sure we will have the same packages version ( very recommended  on running yarn install on ci)
        run: yarn --cwd docs install --frozen-lockfile
      - name: Build website
        run: yarn --cwd docs build
      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./docs/build
          # The following lines assign commit authorship to the official
          # GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: bataevvlad-github-actions[bot]
          user_email: bataevvlad-github-actions[bot]@users.noreply.github.com
